### ISSUE TITLE
Cannot see what I am typing

### ISSUE THREAD

**Issue by maxigarami** [crisp-im/crisp-sdk-android#103]
Hi,

There is a display issue on Android
I'm using a webview to embed the crisp chat.
When I want to type a message, my keyboard appears but the input message textbox stay at the bottom and get hidden by the keyboard. Therefore I cannot see what I am typing

Here is a video showing the issue

https://drive.google.com/file/d/1VjeyVZToUb1ZeJ6iexu7CGxfZMNGsa75/view?usp=sharing

Thank you!

**Comment by Doc1faux** [comment]
Hi @maxigarami and thank your for your feedback.

The new way to embed the Crisp SDK in your app is to use the Android SDK.
But for your usage, we should implement the fragment feature as discussed in #70 and #67 which should come in a future release :)

While waiting for it, I let Crisp team come back for your issue with the Web integration on mobile.
Bu t in order to help them figure out the issue, I quickly tested it this morning embedding the HTML integration code in a local HTML file and loading it in a WebView and it worked like a charm as you can see in the video below :/ 
Maybe it is related to the Android version you used (mine is Android 10), the device you used (mine is a Pixel 3XL) or its display ( mine is 1440x2960 @523 ppi).
I give you also [the sample code](https://github.com/crisp-im/crisp-sdk-android/files/8511625/CrispWeb.zip) I used, I let you match the website Id with yours in `app/src/main/assets/crisp.html`.

https://user-images.githubusercontent.com/2175246/163966979-410f79d5-baa0-46bf-9790-a24306664430.mov

**Comment by maxigarami** [comment]
Hi, Thank you for your answer.
I admit I'm not sure I can implement the solution as I'm using Adalo.com to build my app and I don't have any other option than to embed the crisp chat in a webview.

Thank you for solving the issue in a future release :) I will wait for it

**Comment by Doc1faux** [comment]
Indeed, if you have not the hand on the integration, it's a bit tricky...
Even with the fragment feature added into the SDK, with a WYSIWYG solution like [Adalo](https://www.adalo.com/), I'm not sure you could integrate it :/

**Comment by maxigarami** [comment]
Hi, did you do something?
Now that's what I see

![Screenshot_20220420-225740](https://user-images.githubusercontent.com/103878026/164405658-4d37b36c-1748-4ee1-bd21-7590a163c1ba.png)

Yes, it solves the issue but it's really not good. The chatbox is way too narrow now.
Can you get it back like how it was? It's unusable as it is
Thank you!

**Comment by baptistejamin** [comment]
If you use the Crisp Webview system, it is totally unrelated to this project.

There could be a constraint issue in your project. Did you set the height to 100%?

**Comment by maxigarami** [comment]
I didn't change anything. 
The size changed overnight.
The only thing I m doing in my app is to call the web view
Where can I change the setting for the webview?
Thank you Baptiste

**Comment by Doc1faux** [comment]
I close this issue as it is not related to Android SDK
