### ISSUE TITLE
**Build error**

### ISSUE THREAD

**Issue by swetasrp** [crisp-im/crisp-sdk-android#159]
I have updated SDK to 1.0.15 to use `setSessionSegments`, but I am facing an issue while building the apk. Below is the issue :

`**Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'**`

Can you please provide a solution for this.

**Comment by baptistejamin** [comment]
Hello!What is your build target and your build tools ?Sent from my iPhoneOn 2 Aug 2023, at 14:20, swetasrp ***@***.***> wrote:﻿
I have updated SDK to 1.0.15 to use setSessionSegments, but I am facing an issue while building the apk. Below is the issue :
**Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'**
Can you please provide a solution for this.

**Comment by Doc1faux** [comment]
Hello @swetasrp,

This seems more tied to your dependencies (as `m3` stands for Material 3) or gradle versions rather than the Crisp SDK.
With a quick Google search, you can try updating your dependencies (`appcompat` or `material`) or your `gradle` versions (see [this issue](https://github.com/flutter/flutter/issues/124373)).
For info, the Crisp SDK is using the latest `androidx.appcompat:appcompat:1.6.1`,  `com.google.android.material:material:1.9.0` and gradle `7.5` with plugin `7.4.2` (8.x requires our publishing script to be updated, it will be soon).

Hope this helps.

**Comment by Doc1faux** [comment]
Hi @swetasrp, is the solution I have provided fixed your issue?

I close the issue as it is stale, I let you reopen it if needed ;)
