### ISSUE TITLE
Sending device identifiers

### ISSUE THREAD

**Issue by nfonjeannoel** [crisp-im/crisp-sdk-android#163]
![image](https://github.com/crisp-im/crisp-sdk-android/assets/32074477/aab5d9c3-9941-41a9-a921-4fa2b63f94c4)

Hi there. I got this message from the Play Store after integrating Crisp chat.
The message:

Your app is using device identifiers (IMEI, MAC address, Build Serial, etc.) and sending identifier data to a remote network address.
This issue is commonly (but not only) found in apps using an outdated Advertising SDK. Our analysis suggests that for your APK, this behavior is caused by the Advertising SDK(s) 'bb' although there may be additional SDKs or source code contributing to it. 

To stop receiving this warning, try updating or changing this (these) SDK(s) and check any other SDKs or code that may be using device identifiers.
Sending device identifiers is not a best practice for most use cases and if you're using this identifier for advertising purposes, this may be a violation of Google Play policies and can affect your app's visibility on the Play Store.

So I just need to confirm if or not the message is coming from Crisp chat.
Is it collecting device identifiers?
If yes, is there a way to stop that?
Thanks

**Comment by Doc1faux** [comment]
Hi @nfonjeannoel and thank you for your feedback.

The only thing which seems to be the closest of what Google says is our User-Agent used for REST/WebSocket calls which contains a reference to `Build.VERSION.INCREMENTAL`, I don't know if this is it or if this is against Google Play policies (it does not seem to as this is a software "id", only hardwares one are prohibited, see [Best practices for unique identifiers
](https://developer.android.com/training/articles/user-data-ids#best-practices-android-identifiers)), it seems awkward as we cannot identify a device through this info as this is the build number of the Android OS not the device serial number or IMEI or MAC Address...
Documentation says about it :
> The internal value used by the underlying source control to represent this build. E.g., a perforce changelist number or a git hash.

We build the User-Agent upon:
- app label, 
- versionCode, 
- Android version (`Build.VERSION.RELEASE`),
- Android build (`Build.VERSION.INCREMENTAL`).

It is formatted as `APP_LABEL/APP_VERSION_CODE (Version ANDROID_VERSION (Build ANDROID_BUILD))`.
On our app on an Android 13 Emulator it appears as `Crisp/500052 (Version 13 (Build 10940250))`.

`Build number` can be found in `Settings > About` menu of the phone (see below)

<img src="https://github.com/crisp-im/crisp-sdk-android/assets/2175246/7ed5befe-b84e-4c61-8f1b-72a2fb7bef5a" width="300"/>

Maybe this is the word `Build` which raises a warning on their side or simply its usage? This is the first time we get this warning from our users since the 1st release of the SDK and this `User-Agent` was here since the beginning ^^"

Can you ask Google if this is this is the issue with your app? If this is it, I will remove the `Build.VERSION.INCREMENTAL` from the User-Agent.

Best regards.

**Comment by nfonjeannoel** [comment]
thank you @Doc1faux 
I will message them and get confirmation. Thanks

**Comment by Doc1faux** [comment]
Hi @nfonjeannoel, do you have any update from the Google Play Store team?

While waiting your reply, I close the issue, do not hesitate to reopen it if we need to take action on our side ;)
