### ISSUE TITLE
How to get session callback like iOS SDK

### ISSUE THREAD

**Issue by baronha** [crisp-im/crisp-sdk-android#169]
on iOS. I can get a chat's session from the callback event and I hope Android SDK can do that

IOS Example: 

```swift
CrispSDK.addCallback(Callback.sessionLoaded { sessionId in
    callback([sessionId])
})
```

**Comment by Doc1faux** [comment]
Hi @baronha, sorry for the late reply.
We were focused on the [`2.0.0beta1`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.0beta1) release and this feature was not prioritized.

We are currently working on `2.0.1beta2` and [events callback](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#register-a-callback-on-event) is still not prioritized.
This can be explained because socket is only maintained when the `ChatActivity` is running so not before starting it, not after and not in app background, only in foreground, so its usage is very limited...

However, many of you have requested to get at least the [`session:loaded`](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#session-has-loaded) one: 
- https://github.com/crisp-im/crisp-sdk-android/issues/138#issuecomment-1245541604
- https://github.com/crisp-im/crisp-sdk-android/issues/157#issuecomment-1620548492
- https://github.com/crisp-im/crisp-sdk-android/issues/125#issuecomment-1911668531

So I will discuss with the team if we can add it in this milestone ;)

**Comment by Doc1faux** [comment]
Hi @baronha,

Just to let you know that callbacks are planned for next release ;)

**Comment by baronha** [comment]
> Hi @baronha,
> 
> Just to let you know that callbacks are planned for next release ;)

Good news today. Yay. Many thanks @Doc1faux

**Comment by Doc1faux** [comment]
Hi @baronha, [`v2.0.4`](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.4) is finally here with events callback, including the `session:loaded` many were waiting for!

It should be available in the coming hours on `mavenCentral` ;)
