### ISSUE TITLE
Regarding this issue: The Android chat modal overflows when the keyboard is present.

### ISSUE THREAD

**Issue by muhamien** [crisp-im/crisp-sdk-android#178]
Hi,

I've encountered an issue where the chat modal in the Android version of the app overflows when the keyboard is present. This results in a poor user experience as parts of the chat modal become inaccessible.

Steps to Reproduce:

Open the chat modal on an Android device.
Activate the keyboard by selecting an input field within the modal.
Observe that the chat modal overflows, making parts of it inaccessible.
Expected Behavior:
The chat modal should adjust its size or position to accommodate the keyboard, ensuring that all parts of the modal remain accessible.

Actual Behavior:
The chat modal overflows when the keyboard is present, causing parts of it to be hidden.

Environment:

Android Version: 12
Device Model: Poco X3 NFC
React Native Version: 0.67.5
react-native-crisp-chat-sdk Version: v0.14.1

Link to the Issue:
For similar unanswered discussions, refer to: [GitHub Issue #129](https://github.com/walterholohan/react-native-crisp-chat-sdk/issues/129).

Additional Context:
Any suggestions or workarounds to resolve this issue would be greatly appreciated.

Thank you for your assistance!

**Comment by Doc1faux** [comment]
Hi @muhamien and thank you for your feedback.

I've chosen to pan the modal instead of resizing its content to avoid hiding chat messages (even more if some status/network alert at the top and other alert at the bottom are showing) while the user is typing so he can scroll its chat history if he needs context from a previous message :)

See below a video recording on a (not that) small device, a Nexus 6 if I resize the modal and alerts are showing, it's pretty unreadable :/

https://github.com/crisp-im/crisp-sdk-android/assets/2175246/5a286450-4bbf-436e-9b58-c5d93e68986a

In the current implementation, if the user is typing and needs to access back to the header, obviously he can hides the keyboard by tapping on the "hide keyboard" button at the left of the navigation bar as you did ;)

I think both behaviors have their pros and cons.
We can discuss about it :)

**Comment by muhamien** [comment]
Thank you for your response.

I believe that most smartphone screens nowadays are wider and longer. 
Is there a way to find a compromise for this issue? 

Perhaps we could make the chat modal more responsive by adjusting to the screen size? This could help ensure that the modal doesn't overflow and all parts remain accessible without sacrificing readability.

Additionally, I am using Crisp SDK with [React Native](https://github.com/walterholohan/react-native-crisp-chat-sdk) and [Flutter](https://pub.dev/packages/crisp_chat). Any suggestions or solutions that could address this issue in these frameworks would be greatly appreciated.

**Comment by Doc1faux** [comment]
As status alert (service or network) seems the least important UI component while the user is typing, I could propose to the team to resize the modal instead of panning it and hide temporarily the status alert as shown in the screen record below.
With this solution, modal is not panned and user could scroll their chat history while typing even of smallest screens.

Is this fix could suits your needs?

https://github.com/crisp-im/crisp-sdk-android/assets/2175246/4c75e235-39e1-4178-bd0a-93c7325c8d0b

**Comment by muhamien** [comment]
I have discussed this issue further with my team, and we have decided to follow your suggestion regarding the modal overflow screen.

Thank you!
