### ISSUE TITLE
Emails with single character domains flag as mistyped despite being valid

### ISSUE THREAD

**Issue by john-numerade** [crisp-im/crisp-sdk-android#200]
When using the test email `w16@n.com` the Crisp chat client prompts of a warning of a mistyped email despite the account containing a valid, possible URL. As a result of the warning I am unable to chat with the representative even though it is a real possible email.

Either the checker used within the SDK should allow all valid domains or else a user should still be able to chat with a representative even if their email address isn't correct/valid.

Reference information on single-letter second-level domains. https://en.wikipedia.org/wiki/Single-letter_second-level_domain

Screenshot attached of the message.

![396547245-4ae2d21e-e18a-4d17-9843-e735fc60c6be](https://github.com/user-attachments/assets/62849dee-40a2-40a4-937b-4141a52e8817)

Tested with `crisp-sdk-android` v. `2.0.8`. Previous builds (notably v. `1.0.18`) also contain this issue.

**Comment by baptistejamin** [comment]
This email is not valid and shall not be accepted :)

**Comment by Doc1faux** [comment]
Hi @john-numerade,

This issue is not related to the Crisp Android SDK, so I'll close it.

Crisp Android SDK is performing a very permissive check which uses the pattern provided by the Android SDK itself (see [`android.util.Patterns.EMAIL_ADDRESS`](https://android.googlesource.com/platform/frameworks/base/+/a3bb66a75ef746fc77e9c9dd466afdef7a56996c/core/java/android/util/Patterns.java#158)) that your `w16@n.com` mail address passes.
However, the verification which leads to this error is done by the backend, so common to any Crisp SDK and I cannot change it.
So you can reach our team at [crisp.chat](https://crisp.chat) if you want to address this issue but as @baptistejamin said above, it seems invalid and a NSLookup on it returns nothing...

**Comment by john-numerade** [comment]
Thanks for the context all. It is indeed a test account so provided legitimate single character emails would work this is fine. I closed my associated iOS ticket by referencing this thread.

https://github.com/crisp-im/crisp-sdk-ios/issues/107
